### PR TITLE
Add gridware --latest flag (closes #101)

### LINKED ISSUE #101: Gridware: option install latest version of a package
It would be nice if there was an option to install the latest existing version of a particular package, i.e rather than specifying `apps/iozone/3.420` just specify `--latest apps/iozone` for example.

### PR DESCRIPTION
**Pull request by bobwhitelock**
Adds flag as requested in https://github.com/alces-software/clusterware/issues/101. Based on the rebased version of https://github.com/alces-software/clusterware/pull/154.

### CODE REVIEW

**Comment by mjtko** [comment]
Can you revert cc9762a please? :)

**Comment by bobwhitelock** [comment]
Sure - do you not want editor-specific stuff in them? :)

**Comment by mjtko** [comment]
Actually, I don' t mind too much, but can you relocate somewhere else? Either at end of file or after copyright header. I just find them a bit ugly.

**Comment by mjtko** [comment]
I think I prefer after copyright header.

**Comment by bobwhitelock** [comment]
OK, I'll do that instead. I can remove them entirely and configure things differently if you prefer but was just the easiest way to enable filetype-specific stuff. I do sort of agree though, if everyone did that things would become a mess.

**Comment by mjtko** [comment]
Can you add this to the CHANGELOG too pls?

**Comment by bobwhitelock** [comment]
Made those changes, I've also rebased this on the other branch to avoid a conflict.

**Pull request merged**
