### PR TITLE
Split `alces storage avail` into multiple actions (closes #203)

### LINKED ISSUE #203: Viewing storage configurations setup with alces storage command
_From @wdm78 on May 15, 2016 16:11_

It would be useful to be able to see the names of storage configurations setup by users with the `alces storage configure` command.

_Copied from original issue: alces-software/flight-aws-marketplace#47_

### PR DESCRIPTION
**Pull request by bobwhitelock**
As described in the original issue (#203). Also included is a fix for the `alces storage use` autocompletion; see https://github.com/alces-software/clusterware/commit/03b6775d42b1721420d6cb5eac86394b64fd4f64 for details.

Since this changes the behaviour of the `alces storage avail` command to give what was previously the output for `alces storage avail --backends`, this is a breaking change and any scripts which relied on the previous behaviour will likely be broken by this. If we want Clusterware releases to follow semver then we might want to save this change for Clusterware 2.0.

Alternatively we could decide the chances of anyone depending on this behaviour already are slim; a quick Google/Github search supports this, although of course this isn't definitive.

### CODE REVIEW

**Comment by mjtko** [comment]
Can you add an entry to the changelog for this please?

**Comment by bobwhitelock** [comment]
Done!

**Comment by mjtko** [comment]
Thanks!

**Comment by bobwhitelock** [comment]
Does this not break semver then?

**Pull request merged**
